<template>
  <div>
    <v-overlay
      :model-value="running"
      contained
      persistent
      class="d-flex justify-center align-center"
    >
      <v-icon size="x-large" color="primary"> $vcsProgress </v-icon>
    </v-overlay>
    <v-container class="py-0 px-1">
      <v-row no-gutters>
        <v-col cols="6">
          <VcsLabel html-for="sizeSelect">
            {{ $t('print.pdf.format') }}
          </VcsLabel>
        </v-col>
        <v-col cols="6">
          <VcsSelect
            id="sizeSelect"
            :items="pluginSetup.formatList"
            v-model="pluginState.selectedFormat"
          />
        </v-col>
      </v-row>
      <v-row no-gutters>
        <v-col cols="6">
          <VcsLabel html-for="ppiSelect">
            {{ $t('print.pdf.resolution') }}
          </VcsLabel>
        </v-col>
        <v-col cols="6">
          <VcsSelect
            id="ppiSelect"
            :items="
              pluginSetup.ppiList.map((value) => ({
                value,
                title: `${value} ppi`,
              }))
            "
            v-model="pluginState.selectedPpi"
          />
        </v-col>
      </v-row>
      <v-row v-if="pluginSetup.orientationOptions === 'both'" no-gutters>
        <VcsRadio
          v-model="pluginState.selectedOrientation"
          mandatory
          inline
          :items="[
            { label: $t('print.pdf.portrait'), value: 'portrait' },
            { label: $t('print.pdf.landscape'), value: 'landscape' },
          ]"
        />
      </v-row>
    </v-container>
    <v-divider />
    <v-container class="py-0 px-1">
      <v-row no-gutters>
        <v-col>
          <VcsTextField
            :label="undefined"
            :placeholder="$t('print.pdf.titlePlaceholder')"
            v-model="pluginState.title"
            v-if="pluginSetup.allowTitle"
          />
        </v-col>
      </v-row>
      <v-row no-gutters>
        <v-col>
          <VcsTextArea
            :placeholder="$t('print.pdf.descriptionPlaceholder')"
            class="pt-1 pb-4"
            rows="2"
            v-model="pluginState.description"
            v-if="pluginSetup.allowDescription"
          />
        </v-col>
      </v-row>
    </v-container>
    <v-divider />
    <div class="d-flex w-full justify-end px-2 pt-2 pb-1">
      <VcsFormButton @click="createPdf()" variant="filled">
        <span class="text-uppercase">
          {{ $t('print.pdf.createButton') }}
        </span>
      </VcsFormButton>
    </div>
  </div>
</template>

<style lang="scss" scoped></style>

<script>
  // @ts-check

  import { inject, ref } from 'vue';
  import {
    VcsSelect,
    VcsTextField,
    VcsTextArea,
    VcsLabel,
    VcsFormButton,
    VcsRadio,
    getPluginAssetUrl,
  } from '@vcmap/ui';
  import {
    VOverlay,
    VIcon,
    VContainer,
    VRow,
    VCol,
    VDivider,
  } from 'vuetify/components';
  import { getLogger } from '@vcsuite/logger';
  import PDFCreator from './pdfCreator.js';
  import createAndHandleBlob from '../screenshot/shootScreenAndHandle.js';
  import { name } from '../../package.json';
  import {
    getLogo,
    formatContactInfo,
    getMapInfo,
    getCopyright,
  } from './pdfHelper.js';
  import { getMapAspectRatio } from '../common/util.js';

  export const pdfWindowId = 'create_pdf_window_id';

  export default {
    name: 'PdfWindow',
    components: {
      VcsSelect,
      VcsTextField,
      VcsLabel,
      VcsFormButton,
      VcsTextArea,
      VcsRadio,
      VOverlay,
      VIcon,
      VContainer,
      VRow,
      VCol,
      VDivider,
    },
    setup() {
      /**
       * @type {import("@vcmap/ui").VcsUiApp}
       */
      const app = inject('vcsApp');

      const plugin = app.plugins.getByKey('@vcmap/print');

      const pluginSetup = plugin.config;
      const pluginState = plugin.state;

      // State whether calculation is running.
      const running = ref(false);

      /** Creates pdf by utilizing the PDFCreator. Handling is done by default function in shootScreenAndHandle.js */
      async function createPdf() {
        running.value = true;
        let logo;
        if (pluginSetup.printLogo) {
          try {
            logo = await getLogo(app);
          } catch (error) {
            getLogger(plugin?.name).error(
              `Fetching logo failed with following error: ${error}`,
            );
          }
        }

        /** contact information that can be defined in the plugin config and is printed in the lower left corner */
        let contact;
        if (pluginSetup.contactDetails) {
          contact = formatContactInfo(app, pluginSetup.contactDetails);
        }

        /** information about the map that is printed next to the contact information. Generated by mapHelper.js function. */
        let mapInfo;
        if (pluginSetup.printMapInfo) {
          mapInfo = await getMapInfo(app);
        }

        /**
         * information about the copyright that is rendered in
         * the bottom right corner of the screenshot. Generated by mapHelper.js function.
         */
        let copyright;
        if (pluginSetup.printCopyright) {
          copyright = getCopyright(app);
        }

        // could also be put into styles.js
        const fonts = {
          name: 'RobotoSlab',
          regular: getPluginAssetUrl(
            app,
            name,
            'plugin-assets/fonts/RobotoSlab-Regular.ttf',
          ),
          bold: getPluginAssetUrl(
            app,
            name,
            'plugin-assets/fonts/RobotoSlab-Bold.ttf',
          ),
        };

        const mapAspectRatio = getMapAspectRatio(app.maps.activeMap);

        const pdfCreator = new PDFCreator();
        await pdfCreator.setup({
          orientation: pluginState.selectedOrientation,
          format: pluginState.selectedFormat,
          title: pluginState.title,
          logo,
          imgRatio: mapAspectRatio,
          description: pluginState.description,
          contact,
          mapInfo,
          copyright,
          fonts,
        });
        // after setup possible to execute pdfCreator.create()
        const width =
          pdfCreator.imgPlacement.size.width * pluginState.selectedPpi;
        await createAndHandleBlob(
          app,
          width,
          pdfCreator.create.bind(pdfCreator),
          'map.pdf',
        );
        running.value = false;
      }

      return {
        pluginState,
        pluginSetup,
        running,
        createPdf,
      };
    },
  };
</script>
