<template>
  <div>
    <v-overlay :value="running" absolute :opacity="1" color="basic">
      <v-icon x-large color="primary"> $vcsProgress </v-icon>
    </v-overlay>
    <v-container class="py-0 px-1">
      <v-row no-gutters align="center">
        <v-col cols="7">
          <VcsLabel html-for="sizeSelect" :dense="true">
            {{ $t('print.pdf.format') }}
          </VcsLabel>
        </v-col>
        <v-col>
          <VcsSelect
            id="sizeSelect"
            :items="pluginSetup.formatList"
            v-model="pluginState.selectedFormat"
            :dense="true"
          />
        </v-col>
      </v-row>
      <v-row no-gutters align="center">
        <v-col cols="7">
          <VcsLabel html-for="ppiSelect" :dense="true">
            {{ $t('print.pdf.resolution') }}
          </VcsLabel>
        </v-col>
        <v-col>
          <VcsSelect
            id="ppiSelect"
            :items="pluginSetup.ppiList"
            v-model="pluginState.selectedPpi"
            :dense="true"
          />
        </v-col>
      </v-row>
      <v-row
        v-if="pluginSetup.orientationOptions === 'both'"
        no-gutters
        align="center"
      >
        <VcsRadio
          v-model="pluginState.selectedOrientation"
          mandatory
          row
          :items="[
            { label: $t('print.pdf.portrait'), value: 'portrait' },
            { label: $t('print.pdf.landscape'), value: 'landscape' },
          ]"
        />
      </v-row>
    </v-container>
    <v-divider />
    <v-container class="py-0 px-1">
      <v-row no-gutters align="center">
        <v-col>
          <VcsTextField
            :dense="true"
            :label="undefined"
            :placeholder="$t('print.pdf.titlePlaceholder')"
            v-model="pluginState.title"
            v-if="pluginSetup.allowTitle"
          />
        </v-col>
      </v-row>
      <v-row no-gutters align="center">
        <v-col>
          <VcsTextArea
            :placeholder="$t('print.pdf.descriptionPlaceholder')"
            class="pb-4"
            rows="2"
            v-model="pluginState.description"
            v-if="pluginSetup.allowDescription"
          />
        </v-col>
      </v-row>
    </v-container>
    <v-divider />
    <div class="d-flex w-full justify-end px-2 pt-2 pb-1">
      <VcsFormButton @click="createPdf()" variant="filled">
        <span class="text-uppercase">
          {{ $t('print.pdf.createButton') }}
        </span>
      </VcsFormButton>
    </div>
  </div>
</template>

<style lang="scss" scoped></style>

<script>
  // @ts-check

  import { inject, ref } from 'vue';
  import {
    VcsSelect,
    VcsTextField,
    VcsTextArea,
    VcsLabel,
    VcsFormButton,
    VcsRadio,
    getPluginAssetUrl,
  } from '@vcmap/ui';
  import {
    VOverlay,
    VIcon,
    VContainer,
    VRow,
    VCol,
    VDivider,
  } from 'vuetify/lib';
  import PDFCreator from './pdfCreator.js';
  import createAndHandleBlob from '../screenshot/shootScreenAndHandle.js';
  import { name } from '../../package.json';
  import { getLogo, formatContactInfo, getMapInfo } from './pdfHelper.js';
  import { getMapAspectRatio } from '../common/util.js';

  export const pdfWindowId = 'create_pdf_window_id';

  export default {
    name: 'PdfWindow',
    components: {
      VcsSelect,
      VcsTextField,
      VcsLabel,
      VcsFormButton,
      VcsTextArea,
      VcsRadio,
      VOverlay,
      VIcon,
      VContainer,
      VRow,
      VCol,
      VDivider,
    },
    setup() {
      /**
       * @type {import("@vcmap/ui").VcsUiApp}
       */
      const app = inject('vcsApp');

      const plugin = app.plugins.getByKey('@vcmap/print');

      const pluginSetup = plugin.config;
      const pluginState = plugin.state;

      // State whether calculation is running.
      const running = ref(false);

      /** Creates pdf by utilizing the PDFCreator. Handling is done by default function in shootScreenAndHandle.js */
      async function createPdf() {
        let logo;
        if (pluginSetup.printLogo) {
          logo = await getLogo(app);
        }

        /** contact information that can be defined in the plugin config and is printed in the lower left corner */
        let contact;
        if (pluginSetup.contact) {
          contact = formatContactInfo(app, plugin, pluginSetup.contact);
        }

        /** information about the map that is printed next to the contact information. Generated by mapHelper.js function. */
        let mapInfo;
        if (pluginSetup.printMapInfo) {
          mapInfo = await getMapInfo(app, plugin);
        }

        // could also be put into styles.js
        const fonts = {
          name: 'RobotoSlab',
          regular: getPluginAssetUrl(
            app,
            name,
            'plugin-assets/fonts/RobotoSlab-Regular.ttf',
          ),
          bold: getPluginAssetUrl(
            app,
            name,
            'plugin-assets/fonts/RobotoSlab-Bold.ttf',
          ),
        };

        const mapAspectRatio = getMapAspectRatio(app.maps.activeMap);

        const pdfCreator = new PDFCreator();
        await pdfCreator.setup({
          orientation: pluginState.selectedOrientation,
          format: pluginState.selectedFormat,
          title: pluginState.title,
          logo,
          imgRatio: mapAspectRatio,
          description: pluginState.description,
          contact,
          mapInfo,
          fonts,
        });
        // after setup possible to execute pdfCreator.create()
        const width =
          pdfCreator.imgPlacement.size.width * pluginState.selectedPpi;
        await createAndHandleBlob(
          app,
          running,
          width,
          pdfCreator.create.bind(pdfCreator),
          'map.pdf',
        );
      }

      return {
        pluginState,
        pluginSetup,
        running,
        createPdf,
      };
    },
  };
</script>
